### PR TITLE
Project Finished

### PR DESCRIPTION
**Pull request by BBualdo**
I completed only one of the challenges, because I don't understand keeping calculations in list that user can delete and use for further calculations

### CODE REVIEW

**Comment by antonderegt** [comment]
Hey @BBualdo, I can only see the Calculator.cs file. Could you please check and make sure you uploaded everything to git?

**Comment by BBualdo** [comment]
Hey @antonderegt, I don't know what happened, but now it should be complete

**Review by VocalNight — APPROVED** [review]
Everything looks great, good job on going for the challenges!

I will be approving the project, just gona leave you with a thing to keep in mind in future projects.

image

As you can see, if you use the program a lot, the UI get's a bit clutered.
In the future, find a way to clean the console after certain commands so that the menu/UI is reset.

Again, good job and good luck in your future projects!

**Comment by BBualdo** [comment]
@VocalNight Thank you for your time! You are right, I will keep this in mind in future projects 😁

**Pull request closed without merging**
