### PR TITLE
completed calculator game

### PR DESCRIPTION
**Pull request by dustinlam**

### CODE REVIEW

**Comment by TheCSharpAcademy** [comment]
@dustinlam Have you submitted this project in the platform? I can't see it in the database 🥺

**Comment by dustinlam** [comment]
> @dustinlam Have you submitted this project in the platform? I can't see it in the database 🥺

hello, what do you mean by submitting this project in the platform? how do i do that?

**Comment by dustinlam** [comment]
> @dustinlam Have you submitted this project in the platform? I can't see it in the database 🥺

Hello, I just submitted it! :)

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@dustinlam thanks for submitting! The calculator works fine. 😊

Now,as per the project's requirement, you need to follow microsoft's two part tutorial: https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console?view=vs-2022
image

**Pull request closed without merging**
