### PR TITLE
Project Finished.

### PR DESCRIPTION
**Pull request by HarryjLeigh**
Please review :)

### CODE REVIEW

**Review by chrisjamiecarter — CHANGES_REQUESTED** [review]
Hey @HarryjLeigh 👋,

First of all, great job on your calculator application! 🎉 It’s clear you’ve put a lot of effort into this, and you’re making great progress.

I realize that much of your code likely follows the tutorial, but I have spotted an issue which needs to be resolved before I can review further:

On opening your solution I am greeted with some compiler errors, so cannot run or test your code in its current state.

image

Could you please revisit to try understand and fix any issues, commit and push your changes when complete 🔧 .

Feel free to reach out if you have any questions or if you'd like to collaborate further on any of these points 🆘 .

Thanks and good luck 🍀 ,
@chrisjamiecarter

**Review by chrisjamiecarter — CHANGES_REQUESTED** [review]
Hey @HarryjLeigh 👋,

Well done on getting the updates submitted, great job 🎉 , I can now build, run and test your application.

Fantastic job on completing the challenge requirements 🥇 

The project is 99% of the way there... Unfortunately there is one small issue.

If you test the divide by zero use case, you can see that you get a different error to expected, and then this breaks any further calculations.

**Your application**
image

**Microsoft's application**
csharp-console-calculator-refactored

**Your code**
image

**Microsoft's code**
image

See if you can spot the issue, and provide a fix.

Reach out for support, or refer to the [tutorial](https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console-part-2?view=vs-2022) if you need to.

Nearly there 🏃‍♂️  !

Thanks,
@chrisjamiecarter

**Comment by HarryjLeigh** [comment]
Hello @chrisjamiecarter,

I've added a while loop in the switch case for divide to check if the divisor is zero. If it is, the program prompts the user to enter a non-zero divisor.

**Review by chrisjamiecarter — APPROVED** [review]
Hey @HarryjLeigh 👋,

Excellent job.

Remember that when you have finished a project, give it a polish pass. Pay attention to any code conventions in place, in this instance refer to the C# Academy's [code-conventions](https://thecsharpacademy.com/article/58/code-conventions) page.
This is important as good code conventions/styling ensures consistency, makes your code easier for others to read and maintain, and improves your chances of getting a pull request reviewed and approved.

I will go ahead and mark as approved, keep up the excellent work on the next projects! 😊

Best regards,
@chrisjamiecarter

**Pull request closed without merging**
