### PR TITLE
Finished Microsoft Learn calculator app

### PR DESCRIPTION
**Pull request by ngalantino**

### CODE REVIEW

**Review by chrisjamiecarter — CHANGES_REQUESTED** [review]
Hey @ngalantino ,

Firstly, great job on your calculator application! 🎉 It’s clear you’ve put a lot of effort into this.
I realize that much of your code likely follows the tutorial, but I have a few suggestions that I believe can help you enhance it even further:

**Solution Structure**
Re-read the [Code Reviews](https://thecsharpacademy.com/article/52/code-reviews) academy page. Specifically step 3.
This will make it easier for code-reviewers to pull down and review your code in the future.
When submitting your code review pull request your solution should be contained in a folder named after the project, suffixed with a dot and your github username, as per below:

```
// Template.
.
└── [ProjectName].[GitHubUserName]/
    ├── [SolutionDirectory1]/
    ├── [SolutionDirectory2]/
    └── [ProjectName].sln

// Your example.
.
└── Calculator.ngalantino/
    ├── Calculator/
    ├── CalculatorLibrary/
    └── Calculator.sln
```

**Style Guide Compliance**
Your code is generally well-structured, but to align with best practices, it would be beneficial to follow [Microsoft's style guide](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions) more closely.
This will ensure consistency and make your code easier for others to read and maintain.
- Pay attention to the whitespace in your code.
- Use file-scoped namespaces to save an indentation level
```
// Block-Scoped Namespace
namespace CalculatorLibrary
{
    // Code here.
}
```
vs
```
// File-Scoped Namespace
namespace CalculatorLibrary;
// Code here.
```
- Use interpolated string rather than format strings (CalculatorLibrary.cs line: 71, etc)
```
// Format String
Console.WriteLine("Your result: {0:0.##}\n", result);
```
vs
```
// Interpolated String
Console.WriteLine($"Your result: {result:0.##}\n");
```

**User Experience**
While the current flow of your calculator functions works, there’s an opportunity to improve the user experience.
- You could clear the console each time before you write the menu. This would allow the user to segment an action, maintain readability of the console window and improve the experience for the user.

**Bugs**
Unfortunately, I did spot a bug within your application:

1. DoOperation Bug:
I noticed a small issue with the `DoOperation` method that caused unexpected behaviour.
It looks like when you divide a number by zero, instead of getting the expected message of `This operation will result in a mathematical error` you get `Oh no! An exception occurred trying to do the math. - Details: Token PropertyName in state Property would result in an invalid JSON object. Path 'Operations[0]'.`.

Please address this bug, feel free to reach out if you have any questions or if you'd like to collaborate on any of these points.

Thanks,
@chrisjamiecarter

**Comment by chrisjamiecarter** [comment]
bug-1
bug-1

**Comment by ngalantino** [comment]
Hi @chrisjamiecarter - I fixed the problems you found in my code.  Thanks for the feedback!

**Review by chrisjamiecarter — APPROVED** [review]
Thank you @ngalantino,

What a wonder application to review. 

My only additional suggestion was I think you went a step too far in the console clearing.

I would have:
- asked for input number 1
- asked for input number 2
- asked for calculation operand
- show result. wait for input to continue.
- clear console
- main menu

(In short, remove the `Console.Clear();` from line 47 in Program.cs)

Other than that it is perfect.

Maybe give the challenge tasks a go!?!

You're doing a fantastic job, and my review is only suggestions that I feel will support your growth as a developer.
I will go ahead and mark as approved, keep up the excellent work on the next projects! 😊

Best regards,
@chrisjamiecarter

**Pull request closed without merging**
