### PR TITLE
cleaned up list loop + added extra operations

### PR DESCRIPTION
**Pull request by kwm0304**

### CODE REVIEW

**Review by ananttuli — COMMENTED** [review]
@kwm0304 Nice work! All requirements and almost all challenges are correctly implemented 😄

A few issues:

1. The "10x" operation challenge - The user should only have to input a single number (operand) e.g. `25` and the result should be `10 X 25` `=` `250`. If you want to implement this operation, the program would have to support operations with both 1 or 2 operands. (10x operation is not a requirement of the project, so you could try to implement it correctly or remove it from the program - your choice, let me know)

2. Although mostly fine, there are a few places where code conventions (https://thecsharpacademy.com/article/58/code-conventions) could be followed e.g. "The first line of a file shouldn't be empty.", "Have one empty line between methods." etc.

**Comment by kwm0304** [comment]
> @kwm0304 Nice work! All requirements and almost all challenges are correctly implemented 😄
> 
> A few issues:
> 
> 1. The "10x" operation challenge - The user should only have to input a single number (operand) e.g. `25` and the result should be `10 X 25` `=` `250`. If you want to implement this operation, the program would have to support operations with both 1 or 2 operands. (10x operation is not a requirement of the project, so you could try to implement it correctly or remove it from the program - your choice, let me know)
> 2. Although mostly fine, there are a few places where code conventions (https://thecsharpacademy.com/article/58/code-conventions) could be followed e.g. "The first line of a file shouldn't be empty.", "Have one empty line between methods." etc.

Thanks for reviewing! Should be good now

**Review by ananttuli — APPROVED** [review]
@kwm0304 Approved ✅ Great work completing all challenges. Also, nice use of method overloading for implementing unary & binary operations.

Minor tip for future PRs - [Code conventions #3 Refrain from commenting](https://thecsharpacademy.com/article/58/code-conventions)
E.g. `//operation requires only one input` doesn't give us extra info since your code `if(RequiresOneOperand(op))` is descriptive enough.

All the best for your next project 👍

**Comment by ananttuli** [comment]
Closing this PR since it's been approved cc @kwm0304

**Pull request closed without merging**
