### PR TITLE
Add basic functionality based on requirements

### PR DESCRIPTION
**Pull request by Alvind0**

### CODE REVIEW

**Review by arashi256 — CHANGES_REQUESTED** [review]
Not solution file found (sln) so could not load the project - please upload complete project!

**Comment by Alvind0** [comment]
I'm sorry about that. I'll check and add all files tomorrow morning!

**Comment by arashi256** [comment]
> I'm sorry about that. I'll check and add all files tomorrow morning!

No worries, man :) Whenever you have time!

**Comment by Alvind0** [comment]
Thanks! I don't know how it happened, but all my files are gone from my PC.
Should I remake the project from the start?

**Comment by arashi256** [comment]
Naw, man - I will recreate the project solution for you. This would be a good time for you to practice source/version control on GitHub and make backups!

**Review by arashi256 — APPROVED** [review]
Aside from your little backup disaster and lack of project solution, the actual code works well. I will approve this, but please practice backups and source control. You should be using GitHub or some sort of version control for your projects and then this won't happen :)

**Comment by Alvind0** [comment]
Thank you! I actually was able to use GItHub in the habit tracker project! I'll take care because these things take a lot of time to create. :(

**Review by arashi256 — APPROVED** [review]

**Pull request closed without merging**
