### PR TITLE
first upload

### PR DESCRIPTION
**Pull request by HappyReni**

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@HappyReni Hey there! Thanks for submitting! I'm going to change the requirements to include the second part of this tutorial, since it contains very important skills that you'll benefit from. Do you mind completing it? https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console-part-2?view=vs-2022

**Comment by HappyReni** [comment]
Sure. I will get back to you with part 2 code.

**Comment by TheCSharpAcademy** [comment]
@HappyReni well done! what did you think? Did you already know how to debug, write to files and use a library?

**Comment by HappyReni** [comment]
Yeah, i was already aware of how to debug , write to files from experiences so not that difficult to me. Never used Nuget before but i used pip in Python which is not that unfamilar to me.

**Pull request merged**
