### PR TITLE
A 'Calculator' console application

### PR DESCRIPTION
**Pull request by zen-pb**
Aside from the challenge of dealing with storing past calculations to a list and allowing the user the power to delete the list, I have finished developing the calculator and also implemented additional calculations.

I didn't have time to thoroughly check for inconsistencies because my brain is fried. I'll revisit this repository in the future for refactoring.

### CODE REVIEW

**Comment by TheCSharpAcademy** [comment]
@zen-pb did you submit this project in the Academy's dashboard? I can't see it. 😟

**Comment by zen-pb** [comment]
Hello, thanks for letting me know!

Regarding the project, I just submitted it.

Thanks again!

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@zen-pb Thanks for submitting! Before I review, quick question. Did you follow the tutorials required for this project? Your code is significantly different. 😟

**Comment by TheCSharpAcademy** [comment]
@zen-pb It's been two weeks since the suggested changes, so we're archiving this project. Feel free to reopen the PR and resubmit in the academy when you're ready. 🤓

**Pull request closed without merging**
