### PR TITLE
Project finshed!

### PR DESCRIPTION
**Pull request by CBoton**

### CODE REVIEW

**Comment by VocalNight** [comment]
Hello! Sorry for the delay in reviewing.

If you check the files changed tab next to the title of this pull request you will see there is only one file changed, which is a submodule. That means the push request had some problem.

Could you watch this video and double check?

https://youtu.be/oCvb-Q5lXb8?si=TTH4AlmZU6xJx4e8

**Comment by CBoton** [comment]
Hi VocalNight,

No worries, I'm sure you're all very busy. I followed the video for doing the pull requests, not sure where I am going wrong.

**Comment by VocalNight** [comment]
Well, usually a submodule is comitted when you have a git repository inside another git repository.

So basically let's say you have folders A and B both with a ".git" folder inside them (It's usually a hidden folder, you need to configure windows explorer to show hidden folder to see it)

* B is a subfolder of A
* When you commit A, instead of B showing it's files, it will be seen as a submodule

The usual way to correct this is delete the .git folder from any subfolder of A and make sure all other subfolders don't have it.
Check your project's topmost folder, from where you do the commits/pushes with git, that is the folder you want to have a .git folder. Any other subfolder should not have it and if they do, you need to delete them and redo the commit process.

**Comment by TheCSharpAcademy** [comment]
@CBoton It's been two weeks since the suggested changes, so we're archiving this project. Feel free to reopen the PR and resubmit in the academy when you're ready. 🤓 

@VocalNight You'll get the points regardless. 😎

**Comment by CBoton** [comment]
Hey Sorry I haven't been very active lately, work has been busy and I have
to get my Microsoft AZ900 cert ASAP. Once I'm done with that I'll be back.
Thanks.

**Pull request closed without merging**
