### PR TITLE
Calculator App

### PR DESCRIPTION
**Pull request by N-Endy**
I tried to implement SOLID principles while building the app, different from the structure of the tutorial. Only one challenge has been crossed off. I'll work on the others. Thank you

### CODE REVIEW

**Comment by stevietv** [comment]
Hi @N-Endy - before this is reviewed could you work on fixing up some of the codacy warnings. There is some unused code and usings present in your code that we like to have removed for coding standards.

**Comment by N-Endy** [comment]
Okay, I'll do so. Thank you.

**Comment by stevietv** [comment]
Hi @N-Endy 
Thanks for updating. I appreciate that you took a different approach to the tutorial. Great effort, though I fear that through complicating the approach there are a few things that are fundamental issues right now: 

* You've implemented the CalculatorLibrary in both projects which means that the DoOperation and Finish methods in the CalculatorLibrary.CalculatorLibrary class are never used.
* You've implemented an Interface ICalculatorLibrary which a) defines two methods that are never implemented, and b) is also the interface itself is never implemented.
* The code in CalculatorEngine.DisplayResult() Lines 103 to 107 is never reached. An exception is thrown by the json writer when I try to divide by zero

```
Type a number, and then press 'Enter': 99
Type a number, and then press 'Enter': 0
Choose an operator from the following list:
        a - Add
        s - Subtract
        m - Multiply
        d - Divide
Your option? d
Oh no! An exception occurred while trying to do the math.
 - Details: Token PropertyName in state Property would result in an invalid JSON object. Path 'Operations[0]'.
--------------------------------
```

Do you want to tidy up the handling of divide by zero before I approve this?

**Comment by N-Endy** [comment]
Hello Stevie,

I'm sorry for responding late. I have removed the classes that aren't used,
but I am still figuring out the code in CalculatorEngine.DisplayResult()
that isn't reached. I'll try to do so ad push.

Thank you

**Comment by N-Endy** [comment]
The change has been implemented and all codes are reachable.

**Comment by stevietv** [comment]
this is now approved. ✅ 
Just a tip for next time, make sure that your first project is also in a sub folder, and that the solution is in the main folder. When creating your first project make sure to not tick the box that says put solution and project file in same folder.
The right layout here should have been:

```
Calculator.N-Edy/
├─ Calculator/
│  ├─ Calculator.csproj
├─ CalculatorLibrary/
│  ├─ CalculatorLibrary.csproj
├─ Calculator.N-Edy.sln
```

**Comment by N-Endy** [comment]
Thank you Stevie.
I currently use Visual Studio Code so I use the terminal for creating
projects and solutions.
I'll apply your advice to my next project. Thank you

**Pull request closed without merging**
