### PR TITLE
Finished the tutorial

### PR DESCRIPTION
**Pull request by dinara54**

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@dinara54 Was your project compiling when you submitted? I'm getting this:

image

**Comment by TheCSharpAcademy** [comment]
@dinara54 Let me know if you need help 😊

**Comment by dinara54** [comment]
Thank you, everything is alright!
I just forgot to add Calculator Library folder to git, because I was in the main project folder.

**Comment by TheCSharpAcademy** [comment]
@dinara54 well done! ✅🤓

**Pull request closed without merging**
