### PR TITLE
project done

### PR DESCRIPTION
**Pull request by Lycanthrope8**
All requirements fulfilled

### CODE REVIEW

**Comment by TheCSharpAcademy** [comment]
@Lycanthrope8 Could you please send the link to your own repo as well to speed things up?

**Comment by Lycanthrope8** [comment]
Thank you for your consideration. I will make sure your convenience from next time. 
Here is the link: https://github.com/Lycanthrope8/ConsoleApps-Calculator

**Comment by TheCSharpAcademy** [comment]
@chrisjamiecarter Could you please review the link sent by @Lycanthrope8. I know it's not the best way, but just to speed things up a bit 🫡

**Review by chrisjamiecarter — APPROVED** [review]
Hey @Lycanthrope8 👋 ,

Well done on you Calculator project submission and fulfilling all the requirements!

I will go ahead and mark as approved, keep up the excellent work on the next projects! 😊

Best regards,
@chrisjamiecarter 👍

**Pull request closed without merging**
