### PR TITLE
Ready for Submission.

### PR DESCRIPTION
**Pull request by cyanitol**

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@cyanitol Thanks for submitting! Unfortunatelly your project doesn't build. I can see you have a reference to Newtonsoft.json in your sln file and as far as I know this shouldn't be there.

image

**Comment by cyanitol** [comment]
@TheCSharpAcademy I used git submodules for this and not NuGet.  Just confirmed working on JetBrains Rider and Visual Studio Code:

- **JetBrains Rider:**  Version 2024.1.5 | Build #RD-241.18968.19
- **Visual Studio Code:** Version 1.92.1 (Universal) | Commit: eaa41d57266683296de7d118f574d0c26)  
- **.NET 8.0: ** Version 8.0.303
- **Git:**  Version 2.39.3 (Apple Git-146)
- **macOS Sonoma:** Version 14.6.1 (23G93)
- **Architecture:** Apple M2 Pro (arm64)

I used the following to clone into a fresh repository:

git clone https://github.com/TheCSharpAcademy/CodeReviews.Console.Calculator.git
git fetch origin pull/216/head:216
git checkout 216
git submodule update --init --recursive

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@cyanitol I used the suggested command and got some sort of perm issue. Could you please simply use nuget? Having a package installed as a separate project isn't common practice and makes it much harder for anyone not using Rider.

image

**Comment by TheCSharpAcademy** [comment]
@cyanitol Well done! Project approved! 🤓✅ And well done for completing the challenges! It's very comprehensive 👌🏻

Looking forward to seeing your next projects! 😄

**Pull request closed without merging**
