### PR TITLE
Conrad's calculator app

### PR DESCRIPTION
**Pull request by Radicals27**
Finished the console calculator, minus the trig functions, but including:
Saving number of times opened (to the log file, and it prints at the start of the app to the top)
Saving all calculations for a session to a list
Allowing the user to delete the list
Allowing the user to use previous calculations to do new ones
Power, Square root and 10x as well.

### CODE REVIEW

**Review by chrisjamiecarter — CHANGES_REQUESTED** [review]
Hey @Radicals27 👋 ,

Firstly, excellent work on your calculator submission 🎉 !

However, there are a few things before I can continue.

***

🔴 Looks like you forgot to include your `CalculatorLibrary`

image

image

🟠 **Solution Structure**
As per the academy's [Code Reviews](https://thecsharpacademy.com/article/52/code-reviews) page. You project submission should be as per the below.
```
.
└── [ProjectName].[GitHubUserName]/
    ├── [SolutionDirectory1]/
    ├── [SolutionDirectory2]/
    └── [ProjectName].sln
```
This will make it easier for code-reviewers to pull down and review your code in the future.

So in your case `Calculator.Radicals27`.

***


Please revisit to try understand and fix these issues 🔧 , as the 🔴's relate to the projects requirements and they block my approval.

Feel free to reach out if you have any questions or if you'd like to collaborate further on any of these points 🆘 .

I will go ahead and wait for you to make your changes, commit and push (which will then notify me) 😊 !

Thanks,
@chrisjamiecarter 👍

**Comment by TheCSharpAcademy** [comment]
@Radicals27 Let us know if you need help 😃

**Comment by Radicals27** [comment]
Hi Chris, I just pushed, please let me know if you got the changes.

**Review by chrisjamiecarter — APPROVED** [review]
Hey @Radicals27 👋,

Fantastic work getting your updates pushed through!

***

I will go ahead and mark as approved, keep up the excellent work on the next projects! 😊

Best regards,
@chrisjamiecarter 👍

**Pull request closed without merging**
