### PR TITLE
Initial Commit

### PR DESCRIPTION
**Pull request by CharlieDW**

### CODE REVIEW

**Comment by TheCSharpAcademy** [comment]
@CharlieDW Could you please submit this project in the platform? 😊

**Comment by CharlieDW** [comment]
> @CharlieDW Could you please submit this project in the platform? 😊

Yes sure, I am just still making some changes on it :) I should have created the pr later. my apologies!

**Comment by CharlieDW** [comment]
Hi @TheCSharpAcademy, 

here too with the adding of the extra  operations, I changed the logic a bit in the program file. 
For square root operations, I don't want users to have to fill out two numbers, so made a little if statement there that when a user chooses the square root operation, they will only be prompted to provide one number :)

**Comment by TheCSharpAcademy** [comment]
@CharlieDW I can't remember if I marked this project as complete in the platform, could you please let me know? 😁

**Pull request closed without merging**
