### PR TITLE
re-upload after deleting git folder

### PR DESCRIPTION
**Pull request by Jinboi**

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@Jinboi Hello! Thanks for reuploading 😁 Is the app working for you without a problem? I'm getting this when trying to do a calculation:

image

**Comment by Jinboi** [comment]
@TheCSharpAcademy ,
Hi! 
It wasn't working on my computer either. 

I've fixed it and resubmitting now. 

Capture

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@Jinboi Sorry to be a pain in your ass, but it looks like your json isn't closing properly, could you please fix it? 
image

**Comment by Jinboi** [comment]
It's not working. I'll try to re-build it from the scratch and re-open the PR after.

**Comment by Jinboi** [comment]
Instead of re-opening this PR, I'll create a new PR

**Pull request closed without merging**
