### PR TITLE
Calculator Arian

### PR DESCRIPTION
**Pull request by arian1917**

### CODE REVIEW

**Comment by TheCSharpAcademy** [comment]
@arian1917 I can't see this project in the academy's dashboard. Have you submitted it?

**Comment by arian1917** [comment]
Ups, sorry. I forgot to submit the project. It's done now, sorry for the inconvenience

**Comment by TheCSharpAcademy** [comment]
@arian1917 I still can't see it 😟

These are the only calculators available for review: 
image

**Comment by arian1917** [comment]
I'm having troubles using github, but i submitted the project, i think. 
submit

**Pull request closed without merging**
