### PR TITLE
Calculator App

### PR DESCRIPTION
**Pull request by Lee2150**

### CODE REVIEW

**Comment by Jinboi** [comment]
Hi @Lee2150 ,

Thank you for submitting your project.

While your project looks great, it looks like there's a problem with loading the CalculatorLibrary.

Can you please look into this and re-submit your project?

image

If it helps, don't worry about renameing your folders. 

Thank you and Happy Coding!

Cheers,
-Youngwoo

**Comment by Jinboi** [comment]
Please ping me using @Jinboi when you're ready. Thank you!

**Comment by Lee2150** [comment]
Sorry i had forgotten to change the project reference path after i had renamed the folder. Should be fixed now thank you for the reply. @Jinboi

**Comment by Jinboi** [comment]
Hi @Lee2150 ,

Thank you for resubmitting the project!

I was able to run your program, but something's wrong with your subtraction calculations.

image

I was doing 50 - 3 = 47 but I'm getting -47.

Your project must be doing 3 - 50 = -47 instead of 50 - 3 = 47. 

But I put 50 as my first number so 47 should be the correct answer, instead of -47. 

This should be a quick fix. Can you please re-upload after fixing this bug? 

I should be able able to mark your project as completed after. ^__^ 

Thank you and Happy Coding!

Cheers,
-Youngwoo

**Comment by Lee2150** [comment]
Sorry again, i was careless and didn't check over the code. I had accidentally made the subtraction calculation take away the second input number from the first, instead of the first input number from the second. @Jinboi

**Comment by Jinboi** [comment]
No need to apologies, @Lee2150! Happens to the best of us.  

Your project looks good! I'll mark this as completed. Please move on to the next project!

Thank you and have a good day! 

Enjoy the sun. It's Sunday! Hahahaha 

Cheers,
-Youngwoo

**Pull request closed without merging**
