### PR TITLE
Finished project/tutorial

### PR DESCRIPTION
**Pull request by JsPeanut**

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@JsPeanut I haven't realized you haven't completed this project yet. 😆
Could you please complete part 2, as per requirement.

image

**Comment by JsPeanut** [comment]
Done!

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@JsPeanut Thanks for updating. Did you push the latest changes? At this stage your app is still calling the Calculator.cs class from within the Calculator.JsPeanut project (that one should be deleted), not the one in the CalculatorLibrary.

**Comment by JsPeanut** [comment]
Fixed!

**Pull request merged**
